version: '3'

services:
  flask_app:
    build:
      context: .
    ports:
      - "8000:8000"

  nginx_proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask_app
